use ras_db;
create table COLLEGE (
STUDENT_ID INT auto_increment primary key,
AGE INT,
ADDRESS VARCHAR(50),
GRADE varchar(10),
MOBILE varchar(50),
COURSE VARCHAR(50)
);
SHOW tables;
insert INTO COLLEGE (AGE, ADDRESS, GRADE, MOBILE, COURSE)
VALUES
(18, 'AVADI', 'A+', 8234213349, 'B.COM'),
(17, 'OMR', 'B', 7223334902, 'BCA'),
(20, 'ECR', 'A', 9800124792, 'B.TECH');
SELECT * FROM COLLEGE;
SELECT AGE, GRADE, COURSE FROM COLLEGE;
SELECT count(distinct GRADE) FROM COLLEGE;
SELECT * FROM COLLEGE;
alter TABLE COLLEGE
ADD DOB varchar(50);
SELECT * FROM COLLEGE;
SELECT * FROM COLLEGE WHERE ADDRESS = 'ECR';
SELECT * FROM COLLEGE WHERE ADDRESS = 'ECR' AND AGE > 18;
SELECT * FROM COLLEGE WHERE ADDRESS = 'OMR' OR ADDRESS = 'AVADI';
SELECT * FROM COLLEGE order by AGE DESC;
SELECT * FROM COLLEGE order by AGE ASC;
SELECT * FROM COLLEGE WHERE COURSE = 'BCA';
SELECT ADDRESS, GRADE FROM COLLEGE WHERE AGE BETWEEN 18 AND 20;
SELECT * FROM COLLEGE WHERE ADDRESS IN ('ECR', 'OMR');
alter table COLLEGE
ADD NAME VARCHAR(50);
UPDATE COLLEGE
SET NAME = 'HARI'
WHERE STUDENT_ID = 1;
UPDATE COLLEGE
SET NAME = 'MAHESH'
WHERE STUDENT_ID = 2;
UPDATE COLLEGE
SET NAME = 'ABHI'
WHERE STUDENT_ID =3;
SELECT * FROM COLLEGE;
SELECT * FROM COLLEGE WHERE NAME LIKE '%h';
SELECT * FROM COLLEGE WHERE NAME LIKE 'a%';
SELECT * FROM COLLEGE WHERE NAME LIKE '%AR%';
SELECT * FROM COLLEGE WHERE NAME LIKE '_A%';
SELECT * FROM COLLEGE WHERE NAME LIKE '__H%';
SELECT * FROM COLLEGE WHERE NAME LIKE 'H_%';
SELECT * FROM COLLEGE WHERE NAME LIKE '_H%';
SELECT * FROM COLLEGE WHERE NAME LIKE 'M%H';
SELECT * FROM COLLEGE WHERE AGE = 18;
SELECT * FROM COLLEGE WHERE AGE < 18;
SELECT * FROM COLLEGE WHERE AGE > 18;
SELECT * FROM COLLEGE WHERE AGE <= 18;
SELECT * FROM COLLEGE WHERE AGE >= 18;
SELECT * FROM COLLEGE WHERE NOT GRADE = 'A+';
SELECT * FROM COLLEGE ORDER BY NAME DESC, AGE ASC;
select count(*) AS Total_student from COLLEGE;
SELECT * FROM COLLEGE;
alter TABLE COLLEGE
ADD DOA datetime(6);
SELECT * FROM COLLEGE;
UPDATE COLLEGE
SET DOA = 01/04/2025
WHERE STUDENT_ID = 1;
update COLLEGE
SET DOA = 10/10/2025
where STUDENT_ID = 2;
update COLLEGE
SET DOA = 12/11/2025
where STUDENT_ID = 3;
SELECT * FROM COLLEGE;
alter table COLLEGE
modify DOA datetime(6);
alter table COLLEGE
DROP COLUMN DOA;
SELECT * FROM COLLEGE;
alter TABLE COLLEGE
ADD DOA datetime(6);
SELECT * FROM COLLEGE;
ALTER TABLE COLLEGE
DROP COLUMN DOA;
ALTER TABLE COLLEGE
DROP COLUMN DOB;
SELECT * FROM COLLEGE;
ALTER TABLE COLLEGE
ADD DOA date;
UPDATE COLLEGE
SET DOA = '25-04-01'
WHERE STUDENT_ID = 1;
update COLLEGE
SET DOA = '25-10-12'
where STUDENT_ID = 2;
update COLLEGE
SET DOA = '25-11-04'
where STUDENT_ID = 3;
SELECT * FROM COLLEGE;
select name, course, year(DOA) as ADMIN FROM COLLEGE;
SELECT NAME, datediff(CURDATE(),DOA) AS CURADMIN FROM COLLEGE;
SELECT NAME, date_format(DOA,'%d-%m-%y') as Dateformat from college;
select name, length(name) as Len from college;
select concat(name, '-',course) as conc from college;
select address, replace(address,'OMR','OLD MAHABALIPURAM ROAD') FROM COLLEGE;
select * FROM COLLEGE;
UPDATE COLLEGE SET ADDRESS = replace(address,'OMR','OLD MAHABALIPURAM ROAD')
WHERE ADDRESS LIKE '%OMR%';
select * FROM COLLEGE;
select NAME, substring(NAME,1,3) AS STRG FROM COLLEGE;
USE ras_db;
CREATE TABLE employ (
    emp_id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(50),
    department VARCHAR(30),
    salary INT,
    join_date DATE
);
INSERT INTO employ (name, department, salary, join_date) VALUES
('Arun', 'IT', 45000, '2023-01-10'),
('Priya', 'Finance', 55000, '2022-12-01'),
('Kiran', 'IT', 45000, '2023-03-15'),
('Divya', 'HR', 60000, '2022-11-20'),
('Rahul', 'IT', 70000, '2023-02-05'),
('Sneha', 'Finance', 52000,'2023-04-01'),
('Vikram', 'HR', 48000, '2023-01-25'),
('Anjali', 'IT', 65000, '2023-03-30');
select * from employ;
SELECT name, salary, ROW_NUMBER() OVER (ORDER BY salary DESC) AS row_num                                                       #Gives unique number based on salary (highest to lowest).
FROM employ;
SELECT name, salary, RANK() OVER (ORDER BY salary ASC) AS rank_no
FROM employ;
SELECT name, salary, DENSE_RANK() OVER (ORDER BY salary ASC) AS dense_rank_no
FROM employ;
SELECT name, salary, LAG(salary) OVER (ORDER BY salary) AS previous_salary
FROM employ;
SELECT name, salary, LEAD(salary) OVER (ORDER BY salary) AS next_salary
FROM employ;
SELECT AVG(salary) AS average FROM employ;











